version: '3.8'

services:
  app:
    build: .
    container_name: process-ingestion-service
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=process_user
      - DB_PASSWORD=process_password
      - DB_DATABASE=process_analytics
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15-alpine
    container_name: process-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=process_user
      - POSTGRES_PASSWORD=process_password
      - POSTGRES_DB=process_analytics
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U process_user -d process_analytics']
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: process-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:


